### ISSUE TITLE
Not opening from addon sidebar

### ISSUE THREAD

**Issue by MacgyverJohnson** [rNeomy/clean-uninstall#4]
firefox version 45  ........not working with omni sidebar....pls make it compatible with sidebars all addon i have encountered to this day is compatible with sidebars TIA
Other than that its working great......attached gif shows addons working but Clean uninstall not working from side but unning from about:addons
 ![clean uninstall](https://cloud.githubusercontent.com/assets/17729946/14570456/2606b392-0366-11e6-9ed9-6f48dc6a7684.gif)
btw is it true that from ff48 this addon will be able to differentiate between addon disabling and uninstalling?

**Comment by Quicksaver** [comment]
I can't fix this from within OmniSidebar only, Clean Uninstall's initialization methods are completely out of reach from me. See https://github.com/Quicksaver/OmniSidebar/issues/120 for context. If you ever want to fix this, I'll be glad to make any changes to OSB that you need for it to work there, but I will need to know what they are. Just let me know. :)

**Comment by rNeomy** [comment]
Since there is not enough space in the sidebar area, in the latest version, the UI is opened in a new tab if there is no overlay over an already opened about:addons tab. This should fix this issue as well.

@Quicksaver thanks for the follow up.
@MacgyverJohnson please let me know if there is  still a problem with the new method.

**Comment by Quicksaver** [comment]
@rNeomy you're very welcome, thank you for the quick patch. :)
